<b style="font-size: 25px">DataFrame in pandas</b>

<p>1. From dicts of Series</p>

In [42]:
import pandas as pd

data = {
    "two" : pd.Series([3,4,2], index=["a","b","c"]),
    "one" : pd.Series([1,2,3,4], index=["a","b","c","d"]),
}

df = pd.DataFrame(data)
df.head()

   two  one
a  3.0    1
b  4.0    2
c  2.0    3
d  NaN    4

<p>2. Taking Input from <strong>CSV</strong> File</p>

In [43]:

df = pd.read_csv('./studentMarks.csv')

# Get the data type of the object
df.dtypes

# Printing the data
df.head()

# Mean of all columns
df.mean()

# Median of all columns
df.median()

df.describe()

           Maths    Physics  Chemistry    Biology  Computer Science
count  12.000000  12.000000  12.000000  12.000000         12.000000
mean   61.583333  48.500000  59.000000  57.833333         51.416667
std    23.345073  27.417645  22.074255  15.020188         25.267508
min    19.000000   5.000000  30.000000  40.000000          5.000000
25%    50.500000  34.000000  47.250000  51.500000         34.000000
50%    60.500000  43.500000  55.000000  56.000000         60.000000
75%    79.250000  65.000000  66.000000  62.000000         65.000000
max    94.000000  98.000000  98.000000  98.000000         88.000000

<p>3. Taking input from dict of <strong>ndarrays/list</strong></p>
<describe>All ndarrays must share same length and the index passed should also be of same length, If no index is passed then range(n) will be taken for index array as default, else following exception will be raised</describe>
<p style="font-weight: bold;">ValueError: All arrays must be of the same length</p>

In [44]:

d = {"one": [1,2,3,4], "two": [5,10,11,12]}
df = pd.DataFrame(d, index=["a","b","c","d"])
df.head()

   one  two
a    1    5
b    2   10
c    3   11
d    4   12

<p>4. Taking Input from <strong>Structured and record</strong> array</p>

In [ ]:
import numpy as np

d = np.zeros((2,), dtype = [("A","i4"),("B","f4"),("C","S10")]) # s10 is a numpy byte string of 10bytes, to use normal python string use U10 (Unicode 10byte string)

d[:] = [(1, 2, "Hello"),(3, 4, "World")]

df = pd.DataFrame(d)
df.head()

   A    B         C
0  1  2.0  b'Hello'
1  3  4.0  b'World'

In [5]:
import pandas as pd
df = pd.read_csv('./nba.csv')

val1 = df.loc[3]
val2 = df.iloc[2]

val1.head()

Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Name: 3, dtype: object